AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/**/*'

Rails:
    Enabled: true

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'spec/**/*_spec.rb'

Lint/EndAlignment:
  Enabled: true
  AlignWith: keyword

Lint/Eval:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/FileName:
  Exclude:
    - 'config/deploy/*'

Style/MultilineBlockChain:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/StringLiterals:
  Enabled: false
